<select>
<option>Выберите город</option>
<option>Москва</option>
<option>Санкт-Петербург</option>
<option>Абакан</option>
<option>Анапа</option>
<option>Архангельск</option>
<option>Астрахань</option>
<option>Барнаул</option>
<option>Белгород</option>
<option>Бийск</option>
<option>Благовещенск</option>
<option>Братск</option>
<option>Брянск</option>
<option>Владивосток</option>
<option>Владикавказ</option>
<option>Владимир</option>
<option>Волгоград</option>
<option>Вологда</option>
<option>Воронеж</option>
<option>Выборг</option>
<option>Геленджик</option>
<option>Горно-Алтайск</option>
<option>Грозный</option>
<option>Домбай</option>
<option>Екатеринбург</option>
<option>Ессентуки</option>
<option>Железноводск</option>
<option>Иваново</option>
<option>Ижевск</option>
<option>Иркутск</option>
<option>Йошкар-Ола</option>
<option>Казань</option>
<option>Калининград</option>
<option>Калуга</option>
<option>Кемерово</option>
<option>Киров</option>
<option>Кисловодск</option>
<option>Кострома</option>
<option>Краснодар</option>
<option>Красноярск</option>
<option>Курган</option>
<option>Курск</option>
<option>Кызыл</option>
<option>Липецк</option>
<option>Магадан</option>
<option>Магнитогорск</option>
<option>Майкоп</option>
<option>Мурманск</option>
<option>Набережные Челны</option>
<option>Нальчик</option>
<option>Находка</option>
<option>Нижневартовск</option>
<option>Нижний Новгород</option>
<option>Нижний Тагил</option>
<option>Новгород</option>
<option>Новокузнецк</option>
<option>Новороссийск</option>
<option>Новосибирск</option>
<option>Норильск</option>
<option>Омск</option>
<option>Орел</option>
<option>Оренбург</option>
<option>Пенза</option>
<option>Переславль-Залесский</option>
<option>Пермь</option>
<option>Петрозаводск</option>
<option>Петропавловск-Камчатский</option>
<option>Псков</option>
<option>Пятигорск</option>
<option>Ростов-на-Дону</option>
<option>Рязань</option>
<option>Салехард</option>
<option>Самара</option>
<option>Санкт-Петербург</option>
<option>Саранск</option>
<option>Саратов</option>
<option>Смоленск</option>
<option>Сочи</option>
<option>Ставрополь</option>
<option>Суздаль</option>
<option>Сургут</option>
<option>Сыктывкар</option>
<option>Тамбов</option>
<option>Тверь</option>
<option>Тольятти</option>
<option>Томск</option>
<option>Туапсе</option>
<option>Тула</option>
<option>Тюмень</option>
<option>Улан-Удэ</option>
<option>Ульяновск</option>
<option>Уфа</option>
<option>Хабаровск</option>
<option>Ханты-Мансийск</option>
<option>Чебоксары</option>
<option>Челябинск</option>
<option>Чита</option>
<option>Южно-Сахалинск</option>
<option>Якутск</option>
<option>Ярославль</option>
</select>
